USE appdb;

CREATE TABLE IF NOT EXISTS likes (
  post_id  VARCHAR(64) NOT NULL,
  user_id  VARCHAR(64) NOT NULL,
  reaction VARCHAR(16) NOT NULL DEFAULT 'like',
  PRIMARY KEY (post_id, user_id)
);

GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, LOCK TABLES ON *.* TO 'dbz'@'%';
FLUSH PRIVILEGES;
