[versions]
kafka-clients = "4.3.0"
mysql-connector = "9.7.0"
slf4j = "2.0.16"
junit-jupiter = "6.0.1"
confluent = "8.2.1"
avro = "1.12.1"
flink = "2.2.1"
flink-kafka = "5.0.0-2.2"
spark = "4.2.0"

[libraries]
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-clients" }
mysql-connector = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kafka-avro-serializer = { module = "io.confluent:kafka-avro-serializer", version.ref = "confluent" }
avro = { module = "org.apache.avro:avro", version.ref = "avro" }
kafka-streams = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka-clients" }
kafka-streams-avro-serde = { module = "io.confluent:kafka-streams-avro-serde", version.ref = "confluent" }
flink-streaming-java = { module = "org.apache.flink:flink-streaming-java", version.ref = "flink" }
flink-clients = { module = "org.apache.flink:flink-clients", version.ref = "flink" }
flink-connector-base = { module = "org.apache.flink:flink-connector-base", version.ref = "flink" }
flink-connector-kafka = { module = "org.apache.flink:flink-connector-kafka", version.ref = "flink-kafka" }
flink-avro = { module = "org.apache.flink:flink-avro", version.ref = "flink" }
flink-avro-confluent-registry = { module = "org.apache.flink:flink-avro-confluent-registry", version.ref = "flink" }
spark-sql = { module = "org.apache.spark:spark-sql_2.13", version.ref = "spark" }
spark-avro = { module = "org.apache.spark:spark-avro_2.13", version.ref = "spark" }
